[package]
name = "spider"
version = "0.1.0"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }

[dependencies.gtk]
package = "gtk4"
version = "0.9"
features = ["v4_6"]

[dependencies.adw]
package = "libadwaita"
version = "0.7"
features = ["v1_5"]
